apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nginxapp-cluster
  region: us-east-1
  version: "1.28"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-04cf942f7f58f839a }
      us-east-1b: { id: subnet-04fcafefd2c6e5798 }
      us-east-1c: { id: subnet-0460de7e833a7bbe8 }
    public:
      us-east-1a: { id: subnet-0433e038404b24b7b }
      us-east-1b: { id: subnet-030da9c18225e814f }
      us-east-1c: { id: subnet-049264e238d36cee1 }

managedNodeGroups:
  - name: nginxapp-cluster
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    instanceType: t3.large
    labels: { role: worker }
    ssh:
      publicKeyName: nginxapp
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
